from __future__ import annotations

import json
import time
import uuid
from typing import Any, cast

from app.config import get_settings
from app.db.session import Database
from app.schemas.chat import ChatRequest, ChatResponse, ToolTraceItem
from app.security import sanitize_user_text
from app.services.entity_service import normalize_entity
from app.services.llm_service import ALLOWED_INTENTS, SafeLLMService
from app.services.nrql_builder import Intent, NrqlBuilder
from app.tools.newrelic_tools import TOOL_CATALOG, NewRelicTools


class AgentService:
    """LLM-first New Relic copilot with safe tool execution.

    The LLM always gets the first chance to route the user's message. It can
    choose an allow-listed action/tool, but credentials are never sent to the
    model and every New Relic query is still generated by the backend with safe
    NRQL builders.
    """

    APM_LIST_PHRASES = (
        "lista mis apm",
        "listar mis apm",
        "lista los apm",
        "listar los apm",
        "lista todas",
        "listar todas",
        "todas mis apm",
        "todos mis apm",
        "qué apms",
        "que apms",
        "apms tengo",
        "muéstrame mis apm",
        "muestrame mis apm",
        "ver apms",
        "elige una apm",
        "seleccionar apm",
    )

    ENTITY_REQUIRED_HINTS = (
        "throughput",
        "response",
        "respuesta",
        "latencia",
        "duration",
        "tiempo",
        "error",
        "errores",
        "apdex",
        "p95",
        "p99",
        "percentil",
        "endpoint",
        "transaccion",
        "transacción",
        "deploy",
        "despliegue",
        "log",
        "trace",
        "traza",
        "span",
        "cpu",
        "memoria",
        "database",
        "base de datos",
        "db",
        "grafica",
        "gráfica",
        "grafico",
        "gráfico",
        "analiza",
        "analizar",
        "salud",
        "resumen",
    )

    VAGUE_VISUALIZATION_WORDS = ("grafica", "gráfica", "grafico", "gráfico", "chart", "visualiza", "visualizar")
    PREVIOUS_RESULT_WORDS = (
        "gráfico resultante",
        "grafico resultante",
        "gráfica resultante",
        "grafica resultante",
        "gráfico anterior",
        "grafico anterior",
        "gráfica anterior",
        "grafica anterior",
        "resultado anterior",
        "consulta anterior",
        "lo anterior",
        "esa gráfica",
        "esa grafica",
        "ese gráfico",
        "ese grafico",
        "último gráfico",
        "ultimo grafico",
        "última gráfica",
        "ultima grafica",
        "analiza el gráfico",
        "analiza el grafico",
        "analiza la gráfica",
        "analiza la grafica",
    )
    GENERAL_WORDS = ("general", "salud", "resumen", "métricas clave", "metricas clave", "golden", "todo", "toda la información", "toda la informacion", "estado")
    GREETING_WORDS = ("hola", "buenas", "buen día", "buen dia", "hey", "hello", "hi")
    THANKS_WORDS = ("gracias", "thanks", "thank you", "perfecto", "excelente", "genial")
    IDENTITY_PHRASES = ("quién eres", "quien eres", "qué eres", "que eres", "cómo me ayudas", "como me ayudas")
    CONCEPTUAL_PREFIXES = (
        "qué es",
        "que es",
        "qué significa",
        "que significa",
        "explica",
        "explícame",
        "explicame",
        "cómo funciona",
        "como funciona",
        "para qué sirve",
        "para que sirve",
        "define",
        "diferencia entre",
    )
    NEW_RELIC_TERMS = (
        "new relic",
        "nerdgraph",
        "nrql",
        "apm",
        "apdex",
        "throughput",
        "rpm",
        "latencia",
        "latency",
        "tiempo de respuesta",
        "response time",
        "error rate",
        "tasa de error",
        "transaction",
        "transacción",
        "transaccion",
        "span",
        "trace",
        "traza",
        "log",
        "logs",
        "deploy",
        "despliegue",
        "dashboard",
        "alerta",
        "incidente",
        "golden",
        "métricas",
        "metricas",
        "observabilidad",
    )
    OFF_TOPIC_HINTS = (
        "chiste",
        "receta",
        "poema",
        "canción",
        "cancion",
        "película",
        "pelicula",
        "fútbol",
        "futbol",
        "política",
        "politica",
        "clima",
        "viaje",
        "hotel",
        "restaurante",
        "amor",
        "historia de",
        "matemática",
        "matematica",
        "traduce",
        "traducción",
        "traduccion",
        "cv",
        "curriculum",
    )

    def __init__(self, tools: NewRelicTools | None, db: Database | None = None) -> None:
        self.tools = tools
        self.db = db
        self.llm = SafeLLMService(get_settings())

    async def answer(self, request: ChatRequest) -> ChatResponse:
        clean_message = sanitize_user_text(request.message)
        session_id = self.db.ensure_chat_session(request.session_id, clean_message[:80], selected_entity_guid=request.entity_guid) if self.db else str(uuid.uuid4())
        if self.db:
            self.db.save_chat_message(session_id, "user", clean_message)

        traces: list[ToolTraceItem] = []
        history = self.db.get_chat_messages(session_id) if self.db else []
        last_result = self.db.get_latest_query_run(session_id, request.entity_guid) if self.db else None

        route = await self._llm_route(request, clean_message, traces, history, last_result)
        if route is None:
            route = self._fallback_route(clean_message, request, last_result)

        result = await self._execute_route(route, request, session_id, traces, clean_message, last_result)
        self._save_assistant(session_id, result)
        return result

    def _save_assistant(self, session_id: str, result: ChatResponse) -> None:
        if self.db:
            self.db.save_chat_message(session_id, "assistant", result.answer, result.model_dump(mode="json"))

    async def _llm_route(
        self,
        request: ChatRequest,
        clean_message: str,
        traces: list[ToolTraceItem],
        history: list[dict[str, Any]],
        last_result: dict[str, Any] | None,
    ) -> dict[str, Any] | None:
        start = time.perf_counter()
        route = await self.llm.route_request(
            message=clean_message,
            context={
                "account_id": request.account_id,
                "entity_guid": request.entity_guid,
                "entity_name": request.entity_name,
                "time_range": request.time_range.model_dump(),
            },
            history=history,
            last_result=last_result,
        )
        duration_ms = (time.perf_counter() - start) * 1000
        preview: dict[str, Any] = {
            "provider": self.llm.provider,
            "model": self.llm.model,
            "llm_enabled": self.llm.enabled,
            "has_previous_query_result": bool(last_result),
        }
        if route:
            preview.update(
                {
                    "action": route.get("action"),
                    "intents": route.get("intents", []),
                    "confidence": route.get("confidence"),
                    "needs_tool": route.get("needs_tool"),
                    "answer_from_llm": bool(route.get("answer")),
                }
            )
        else:
            preview["fallback_reason"] = self.llm.last_error or "LLM returned no valid route."
        traces.append(
            ToolTraceItem(
                tool="llm_router",
                input={
                    "provider": self.llm.provider,
                    "model": self.llm.model,
                    "message_chars": len(clean_message),
                    "has_account": bool(request.account_id),
                    "has_selected_apm": bool(request.entity_guid),
                },
                ok=route is not None,
                duration_ms=duration_ms,
                safe_output_preview=preview,
            )
        )
        return route

    def _fallback_route(self, clean_message: str, request: ChatRequest, last_result: dict[str, Any] | None) -> dict[str, Any]:
        """Secondary path used only when the LLM is disabled or fails."""
        lower = clean_message.lower()
        if self._references_previous_result(lower) and last_result:
            return {"action": "analyze_last_result", "intents": [], "answer": None, "confidence": 0.4, "needs_tool": True}
        if self._asks_for_capabilities(lower):
            return {"action": "capabilities", "intents": [], "answer": None, "confidence": 0.4, "needs_tool": True}
        if self._is_greeting(lower):
            target = f" sobre {request.entity_name}" if request.entity_name else ""
            return {
                "action": "answer_direct",
                "answer": (
                    f"¡Hola! Soy OpsPilot, tu copiloto para New Relic{target}. "
                    "Puedo analizar APMs, ejecutar NRQL seguro, generar gráficas y explicar resultados dentro del contexto de observabilidad."
                ),
                "intents": [],
                "confidence": 0.3,
                "needs_tool": False,
            }
        if self._is_thanks(lower):
            return {
                "action": "answer_direct",
                "answer": "Con gusto. Puedo seguir ayudándote con APMs, errores, latencia, throughput, deploys, logs, trazas o NRQL en New Relic.",
                "intents": [],
                "confidence": 0.3,
                "needs_tool": False,
            }
        if self._asks_identity(lower):
            return {
                "action": "answer_direct",
                "answer": (
                    "Soy OpsPilot for New Relic: un copiloto de observabilidad. "
                    "Primero interpreto tu intención con el LLM y, si hacen falta datos reales, ejecuto herramientas seguras contra New Relic."
                ),
                "intents": [],
                "confidence": 0.3,
                "needs_tool": False,
            }
        if self._is_conceptual_new_relic_question(lower):
            return {"action": "answer_direct", "answer": self._fallback_contextual_answer(clean_message), "intents": [], "confidence": 0.3, "needs_tool": False}
        if self._is_off_topic(lower):
            return {"action": "new_relic_only", "answer": None, "intents": [], "confidence": 0.3, "needs_tool": False}
        if self._asks_for_apm_list(lower):
            return {"action": "list_apms", "intents": [], "answer": None, "confidence": 0.4, "needs_tool": True}
        if any(phrase in lower for phrase in ["fuentes de datos", "data sources", "inventario de datos", "qué eventos", "que eventos", "atributos disponibles"]):
            return {"action": "data_sources", "intents": [], "answer": None, "confidence": 0.4, "needs_tool": True}

        deterministic_intents = NrqlBuilder.infer_intents(clean_message)
        if deterministic_intents:
            return {"action": "run_nrql", "intents": deterministic_intents, "answer": None, "confidence": 0.4, "needs_tool": True}
        if any(word in lower for word in self.GENERAL_WORDS):
            return {"action": "run_nrql", "intents": ["golden_metrics"], "answer": None, "confidence": 0.4, "needs_tool": True}
        if self._is_vague_visualization_request(lower, []):
            return {"action": "clarify", "intents": [], "clarifying_question": self._default_clarification(request.entity_name), "confidence": 0.4, "needs_tool": False}
        return {"action": "clarify", "intents": [], "clarifying_question": self._default_clarification(request.entity_name), "confidence": 0.2, "needs_tool": False}

    async def _execute_route(
        self,
        route: dict[str, Any],
        request: ChatRequest,
        session_id: str,
        traces: list[ToolTraceItem],
        clean_message: str,
        last_result: dict[str, Any] | None,
    ) -> ChatResponse:
        action = route.get("action")
        if action == "answer_direct":
            answer = route.get("answer") or await self.llm.answer_contextual(question=clean_message, context={"entity_name": request.entity_name, "account_id": request.account_id})
            return ChatResponse(ok=True, session_id=session_id, answer=answer or self._fallback_contextual_answer(clean_message), tool_traces=traces, suggestions=self._suggestions())

        if action == "new_relic_only":
            answer = route.get("answer") or (
                "Puedo ayudarte, pero mantengo este chat enfocado en New Relic y observabilidad. "
                "Reformula tu pregunta hacia APMs, métricas, errores, logs, trazas, deploys, alertas o NRQL."
            )
            return ChatResponse(ok=True, session_id=session_id, answer=answer, tool_traces=traces, action="new_relic_only", suggestions=self._suggestions())

        if action == "capabilities":
            return self._capabilities_response(session_id, traces)

        if action == "list_apms":
            return await self._apm_selection_response(request, session_id, traces, reason="llm_route_list")

        if action == "data_sources":
            if not request.entity_guid:
                return await self._apm_selection_response(request, session_id, traces, reason="data_sources_entity_required")
            return await self._data_sources_response(request, session_id, traces)

        if action == "analyze_last_result":
            return await self._analyze_last_result_response(request, session_id, traces, clean_message, last_result)

        if action == "clarify":
            question = route.get("clarifying_question") or self._default_clarification(request.entity_name)
            return self._clarification_response(session_id, question, traces)

        if action == "run_nrql":
            return await self._metrics_response(request, session_id, traces, clean_message, route)

        return self._clarification_response(session_id, self._default_clarification(request.entity_name), traces)

    @classmethod
    def _is_greeting(cls, lower: str) -> bool:
        stripped = lower.strip(" !¡¿?.")
        if stripped in cls.GREETING_WORDS:
            return True
        if cls._has_new_relic_term(lower):
            return False
        return len(stripped.split()) <= 3 and any(stripped.startswith(word + " ") for word in cls.GREETING_WORDS)

    @classmethod
    def _is_thanks(cls, lower: str) -> bool:
        stripped = lower.strip(" !¡¿?.")
        return stripped in cls.THANKS_WORDS

    @classmethod
    def _asks_identity(cls, lower: str) -> bool:
        return any(phrase in lower for phrase in cls.IDENTITY_PHRASES)

    @classmethod
    def _has_new_relic_term(cls, lower: str) -> bool:
        return any(term in lower for term in cls.NEW_RELIC_TERMS)

    @classmethod
    def _is_conceptual_new_relic_question(cls, lower: str) -> bool:
        if not cls._has_new_relic_term(lower):
            return False
        return lower.strip().startswith(cls.CONCEPTUAL_PREFIXES)

    @classmethod
    def _is_off_topic(cls, lower: str) -> bool:
        if cls._has_new_relic_term(lower):
            return False
        return any(hint in lower for hint in cls.OFF_TOPIC_HINTS)

    @classmethod
    def _references_previous_result(cls, lower: str) -> bool:
        return any(phrase in lower for phrase in cls.PREVIOUS_RESULT_WORDS)

    @staticmethod
    def _fallback_contextual_answer(question: str) -> str:
        lower = question.lower()
        if "apdex" in lower:
            return "Apdex en New Relic mide satisfacción de usuarios con base en tiempos de respuesta: satisfecho, tolerable y frustrado. Es útil para priorizar degradaciones de experiencia junto con latencia, throughput y tasa de error."
        if "throughput" in lower or "rpm" in lower:
            return "Throughput en New Relic representa volumen de solicitudes o transacciones, normalmente en requests por minuto. Sirve para correlacionar carga con latencia, errores y saturación."
        if "nrql" in lower:
            return "NRQL es el lenguaje de consulta de New Relic para leer datos de telemetría. En OpsPilot lo uso de forma read-only y con builders seguros para evitar consultas destructivas o fuera de contexto."
        if "error" in lower:
            return "En New Relic conviene analizar errores por tasa, clase, mensaje, transacción afectada y cambio temporal. Así puedes distinguir picos aislados de regresiones o fallos persistentes."
        return "Puedo explicarlo dentro del contexto de New Relic y observabilidad. Para convertirlo en datos reales, selecciona una cuenta/APM y pide una métrica, una gráfica o una consulta NRQL segura."

    @staticmethod
    def _credentials_required_response(session_id: str) -> ChatResponse:
        return ChatResponse(
            ok=False,
            session_id=session_id,
            answer="Para consultar datos reales necesito una sesión de New Relic activa. Conecta tus credenciales o selecciona un perfil válido; mientras tanto puedo responder ayuda conceptual sobre New Relic.",
            action="credentials_required",
            suggestions=["Conectar New Relic", "Qué puedes hacer", "Qué es NRQL", "Qué es Apdex"],
        )

    @staticmethod
    def _account_required_response(session_id: str, traces: list[ToolTraceItem]) -> ChatResponse:
        return ChatResponse(
            ok=False,
            session_id=session_id,
            answer="Necesito una cuenta de New Relic seleccionada antes de consultar datos. Conecta New Relic o elige una cuenta en la barra superior.",
            tool_traces=traces,
            action="account_required",
            suggestions=["Listar mis APMs", "Revisar sesión"],
        )

    @classmethod
    def _asks_for_apm_list(cls, lower: str) -> bool:
        return any(phrase in lower for phrase in cls.APM_LIST_PHRASES) or ("apm" in lower and any(word in lower for word in ["lista", "listar", "muestra", "muéstrame", "tengo", "disponibles"]))

    @staticmethod
    def _asks_for_capabilities(lower: str) -> bool:
        return any(phrase in lower for phrase in ["herramientas", "tools", "capacidades", "qué puedes hacer", "que puedes hacer"])

    @classmethod
    def _needs_selected_entity(cls, lower: str) -> bool:
        return any(hint in lower for hint in cls.ENTITY_REQUIRED_HINTS)

    @classmethod
    def _is_vague_visualization_request(cls, lower: str, intents: list[Intent]) -> bool:
        if intents:
            return False
        if not any(word in lower for word in cls.VAGUE_VISUALIZATION_WORDS):
            return False
        if cls._references_previous_result(lower):
            return False
        return not any(word in lower for word in cls.GENERAL_WORDS)

    async def _apm_selection_response(self, request: ChatRequest, session_id: str, traces: list[ToolTraceItem], reason: str) -> ChatResponse:
        if not self.tools:
            result = self._credentials_required_response(session_id)
            result.tool_traces = traces
            return result
        start = time.perf_counter()
        response = await self.tools.list_apm_entities(account_ids=[request.account_id] if request.account_id else None)
        rows = response.data.get("rows", []) if response.data else []
        entities = [normalize_entity(row) for row in rows]
        traces.append(
            ToolTraceItem(
                tool="list_apm_entities",
                input={"account_id": request.account_id, "reason": reason},
                ok=response.ok,
                duration_ms=(time.perf_counter() - start) * 1000,
                safe_output_preview={"entities": len(entities), "all_returned": True},
            )
        )
        if not response.ok:
            answer = response.error.message if response.error else "No pude listar APMs desde New Relic."
            return ChatResponse(ok=False, session_id=session_id, answer=answer, tool_traces=traces, suggestions=self._suggestions())
        if not entities:
            answer = "No encontré APMs accesibles con las credenciales actuales. Verifica permisos, región y que las aplicaciones estén reportando en New Relic."
            return ChatResponse(ok=True, session_id=session_id, answer=answer, tool_traces=traces, entities=[], action="select_apm", suggestions=["Revisar sesión", "Buscar entidades"])

        if reason in {"entity_required", "data_sources_entity_required"}:
            answer = (
                f"Para responder esa consulta necesito una APM específica. Encontré {len(entities)} APMs accesibles; "
                "selecciona una en la lista completa y repetiré la consulta usando esa entidad como contexto."
            )
        else:
            answer = (
                f"Encontré {len(entities)} APMs accesibles. Te muestro todas en la lista interactiva. "
                "Selecciona una APM para fijarla como contexto del copiloto."
            )
        return ChatResponse(
            ok=True,
            session_id=session_id,
            answer=answer,
            tool_traces=traces,
            rows=[entity.model_dump(mode="json") for entity in entities],
            entities=entities,
            action="select_apm",
            suggestions=["Grafica throughput", "Grafica tiempo de respuesta", "Dame errores recientes", "Transacciones más lentas"],
        )

    def _capabilities_response(self, session_id: str, traces: list[ToolTraceItem]) -> ChatResponse:
        response = self.tools.tool_catalog() if self.tools else None
        rows = response.data.get("rows", []) if response else TOOL_CATALOG
        grouped: dict[str, list[str]] = {}
        for row in rows:
            grouped.setdefault(str(row.get("category", "general")), []).append(f"{row.get('name')}: {row.get('description')}")
        parts = ["Estas son las herramientas disponibles para operar sobre New Relic:"]
        for category, items in grouped.items():
            parts.append(f"\n{category.title()}: " + "; ".join(items[:10]))
        answer = "\n".join(parts)
        traces.append(ToolTraceItem(tool="tool_catalog", input={}, ok=True, duration_ms=0, safe_output_preview={"tools": len(rows)}))
        return ChatResponse(ok=True, session_id=session_id, answer=answer, tool_traces=traces, suggestions=self._suggestions())

    async def _data_sources_response(self, request: ChatRequest, session_id: str, traces: list[ToolTraceItem]) -> ChatResponse:
        if not self.tools:
            result = self._credentials_required_response(session_id)
            result.tool_traces = traces
            return result
        if not request.account_id:
            return self._account_required_response(session_id, traces)
        start = time.perf_counter()
        response = await self.tools.detect_apm_data_sources(request.account_id, request.entity_guid, since=request.time_range.since)
        traces.append(
            ToolTraceItem(
                tool="detect_apm_data_sources",
                input={"account_id": request.account_id, "entity_guid": request.entity_guid},
                ok=response.ok,
                duration_ms=(time.perf_counter() - start) * 1000,
                safe_output_preview={"sources": len(response.data.get("rows", [])) if response.data else 0},
            )
        )
        rows = response.data.get("rows", []) if response.data else []
        if rows:
            summary = ", ".join(f"{row.get('event_type')} ({row.get('count')} eventos)" for row in rows)
            answer = f"Detecté estas fuentes útiles para la APM seleccionada: {summary}. Usaré la fuente principal detectada para generar NRQL más preciso."
        else:
            answer = "No detecté eventos recientes para esta APM en el rango actual. Prueba ampliar el rango o revisar si la entidad está reportando."
        return ChatResponse(ok=response.ok, session_id=session_id, answer=answer, tool_traces=traces, rows=rows, suggestions=self._suggestions())

    async def _analyze_last_result_response(
        self,
        request: ChatRequest,
        session_id: str,
        traces: list[ToolTraceItem],
        clean_message: str,
        last_result: dict[str, Any] | None,
    ) -> ChatResponse:
        if not last_result:
            return ChatResponse(
                ok=True,
                session_id=session_id,
                answer=(
                    "No encuentro un gráfico o consulta anterior en esta conversación para analizar. "
                    "Genera primero una gráfica de New Relic, por ejemplo throughput, tiempo de respuesta o una vista general de métricas clave."
                ),
                tool_traces=traces,
                action="no_previous_result",
                suggestions=self._suggestions(),
            )
        rows = last_result.get("rows") or []
        visualizations = last_result.get("visualizations") or []
        nrql = str(last_result.get("nrql") or "")
        answer = await self._llm_explain(clean_message, rows, visualizations, nrql, traces, mode="analyze_last_result")
        if not answer:
            answer = self._metrics_answer(rows=rows, nrql=nrql, chart_count=len(visualizations), entity_name=request.entity_name, intents=[])
        return ChatResponse(
            ok=True,
            session_id=session_id,
            answer=answer,
            tool_traces=traces,
            visualizations=visualizations,
            rows=rows,
            nrql=nrql,
            action="analyze_last_result",
            suggestions=self._suggestions(),
        )

    async def _metrics_response(self, request: ChatRequest, session_id: str, traces: list[ToolTraceItem], clean_message: str, route: dict[str, Any]) -> ChatResponse:
        if not self.tools:
            result = self._credentials_required_response(session_id)
            result.tool_traces = traces
            return result
        if not request.account_id:
            return self._account_required_response(session_id, traces)

        lower = clean_message.lower()
        intents = self._choose_intents(clean_message, route)
        if self._is_vague_visualization_request(lower, intents):
            return self._clarification_response(session_id, route.get("clarifying_question") or self._default_clarification(request.entity_name), traces)
        if not intents:
            return self._clarification_response(session_id, route.get("clarifying_question") or self._default_clarification(request.entity_name), traces)
        if not request.entity_guid and self._needs_selected_entity_for_intents(intents):
            return await self._apm_selection_response(request, session_id, traces, reason="entity_required")

        all_rows: list[dict[str, Any]] = []
        all_visualizations: list[dict[str, Any]] = []
        nrql_parts: list[str] = []
        ok = True
        error_messages: list[str] = []

        for intent in intents[:5]:
            plan_nrql = NrqlBuilder.build(
                intent,
                app_name=request.entity_name,
                entity_guid=request.entity_guid,
                since=request.time_range.since,
                until=request.time_range.until,
                timezone=request.time_range.timezone or "UTC",
                event_type=request.transaction_event_type or "Transaction",
                transaction_name_attribute=request.transaction_name_attribute or "name",
                step=request.time_range.step,
            )
            start = time.perf_counter()
            tool_response = await self.tools.run_nrql(
                request.account_id,
                plan_nrql.nrql,
                entity_guid=request.entity_guid,
                title=plan_nrql.title,
                chart_type=plan_nrql.chart_type,
                time_range=request.time_range.model_dump(),
            )
            rows = tool_response.data.get("rows", []) if tool_response.data else []
            resolved_nrql = tool_response.nrql or plan_nrql.nrql
            fallback_used = bool(tool_response.data.get("original_nrql")) if tool_response.data else False
            traces.append(
                ToolTraceItem(
                    tool="run_nrql",
                    input={"account_id": request.account_id, "entity_guid": request.entity_guid, "intent": intent},
                    ok=tool_response.ok,
                    duration_ms=(time.perf_counter() - start) * 1000,
                    safe_output_preview={"rows": len(rows), "nrql": resolved_nrql, "fallback_used": fallback_used},
                )
            )
            nrql_parts.append(resolved_nrql)
            if tool_response.ok:
                all_rows.extend(rows)
                all_visualizations.extend(tool_response.visualizations)
                if self.db:
                    self.db.save_query_run(session_id, request.account_id, request.entity_guid, resolved_nrql, rows, tool_response.visualizations)
            else:
                ok = False
                if tool_response.error:
                    error_messages.append(tool_response.error.message)

        nrql_joined = "\n\n-- siguiente consulta --\n".join(nrql_parts)
        unique_errors = list(dict.fromkeys(error_messages))
        if ok or all_rows or all_visualizations:
            answer = await self._llm_explain(clean_message, all_rows, all_visualizations, nrql_joined, traces, mode="fresh_query")
            if not answer:
                answer = self._metrics_answer(rows=all_rows, nrql=nrql_joined, chart_count=len(all_visualizations), entity_name=request.entity_name, intents=intents)
            if not ok and unique_errors:
                answer += "\n\nNota: algunas consultas no respondieron para este rango y se omitieron del resultado final. " + " ".join(unique_errors[:2])
            final_ok = True
        else:
            final_ok = False
            answer = (
                "No pude generar una gráfica usable para ese rango. Probé consultas seguras contra New Relic, "
                "pero la API devolvió errores para todas. Prueba un rango un poco más corto o una métrica específica; "
                "también dejé las consultas en el panel técnico para revisarlas."
            )
            if unique_errors:
                answer += " Detalle: " + " ".join(unique_errors[:2])

        return ChatResponse(ok=final_ok, session_id=session_id, answer=answer, tool_traces=traces, visualizations=all_visualizations, rows=all_rows, nrql=nrql_joined, suggestions=self._suggestions())

    async def _llm_explain(
        self,
        question: str,
        rows: list[dict[str, Any]],
        visualizations: list[dict[str, Any]],
        nrql: str,
        traces: list[ToolTraceItem],
        mode: str,
    ) -> str | None:
        start = time.perf_counter()
        answer = await self.llm.explain_metrics(question=question, rows=rows, visualizations=visualizations, nrql=nrql, mode=mode)
        traces.append(
            ToolTraceItem(
                tool="llm_explain",
                input={"provider": self.llm.provider, "model": self.llm.model, "mode": mode, "row_count": len(rows), "chart_count": len(visualizations)},
                ok=bool(answer),
                duration_ms=(time.perf_counter() - start) * 1000,
                safe_output_preview={
                    "provider": self.llm.provider,
                    "model": self.llm.model,
                    "mode": mode,
                    "answer_chars": len(answer or ""),
                    "fallback_reason": None if answer else (self.llm.last_error or "LLM returned no explanation."),
                },
            )
        )
        return answer

    @staticmethod
    def _choose_intents(clean_message: str, route: dict[str, Any]) -> list[Intent]:
        raw_route_intents = route.get("intents") or []
        route_intents = [cast(Intent, item) for item in raw_route_intents if isinstance(item, str) and item in ALLOWED_INTENTS]
        if route_intents:
            return route_intents[:5]
        deterministic_intents = NrqlBuilder.infer_intents(clean_message)
        if deterministic_intents:
            return deterministic_intents[:5]
        lower = clean_message.lower()
        if any(word in lower for word in AgentService.GENERAL_WORDS):
            return ["golden_metrics"]
        return []

    @staticmethod
    def _needs_selected_entity_for_intents(intents: list[Intent]) -> bool:
        return bool(intents)

    @staticmethod
    def _default_clarification(entity_name: str | None = None) -> str:
        target = f" para {entity_name}" if entity_name else ""
        return (
            f"¿Qué métrica quieres graficar{target}? Puedo generar throughput, tiempo de respuesta, tasa de error, Apdex, percentiles, "
            "transacciones lentas, logs, trazas, base de datos, dependencias externas o una vista general de métricas clave."
        )

    def _clarification_response(self, session_id: str, question: str, traces: list[ToolTraceItem]) -> ChatResponse:
        return ChatResponse(
            ok=True,
            session_id=session_id,
            answer=question,
            tool_traces=traces,
            action="clarify_metric",
            suggestions=[
                "Grafica throughput minuto a minuto",
                "Grafica tiempo de respuesta minuto a minuto",
                "Grafica tasa de error minuto a minuto",
                "Dame una vista general de métricas clave",
                "Dame transacciones más lentas con p95 y p99",
            ],
        )

    @staticmethod
    def _metrics_answer(rows: list[dict[str, Any]], nrql: str, chart_count: int, entity_name: str | None = None, intents: list[Intent] | None = None) -> str:
        if not rows:
            return "New Relic no devolvió datos para esa consulta. Dejé la query visible para que puedas revisarla y probar un rango más amplio."
        target = f" para {entity_name}" if entity_name else ""
        requested = ", ".join((intents or []))
        suffix = f" Intención detectada: {requested}." if requested else ""
        return f"Ejecuté la consulta{target} contra New Relic y recibí {len(rows)} filas reales. Generé {chart_count} visualización(es) alineadas con tu pregunta.{suffix} Puedes ver/copiar el NRQL y exportar los datos."

    @staticmethod
    def _suggestions() -> list[str]:
        return [
            "Lista mis APMs",
            "Grafica throughput minuto a minuto",
            "Grafica tiempo de respuesta minuto a minuto",
            "Dame transacciones clave con p95, p99 y tasa de error",
            "Busca errores recientes por clase y mensaje",
            "Detecta fuentes de datos y atributos disponibles",
        ]

    @staticmethod
    async def sse_events(response: ChatResponse):
        yield f"event: message\ndata: {json.dumps({'type': 'answer_delta', 'content': response.answer})}\n\n"
        if response.nrql:
            yield f"event: tool\ndata: {json.dumps({'type': 'nrql', 'nrql': response.nrql})}\n\n"
        yield f"event: done\ndata: {response.model_dump_json()}\n\n"
